belongsTo(pig0,struct4).
belongsTo(stone1,struct0).
belongsTo(stone2,struct1).
belongsTo(stone3,struct2).
belongsTo(stone6,struct4).
belongsTo(wood0,struct0).
belongsTo(wood4,struct3).
belongsTo(wood5,struct4).
bird(redbird0).
bird(redbird1).
bird(redbird2).
bird(redbird3).
birdOrder(redbird0,3).
birdOrder(redbird1,1).
birdOrder(redbird2,2).
birdOrder(redbird3,0).
canCollapse(struct3,struct2).
canCollapse(struct4,struct3).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
hasColor(redbird0,red).
hasColor(redbird1,red).
hasColor(redbird2,red).
hasColor(redbird3,red).
hasForm(stone1,bar).
hasForm(stone2,bar).
hasForm(stone3,bar).
hasForm(stone6,bar).
hasForm(wood0,bar).
hasForm(wood4,block).
hasForm(wood5,bar).
hasMaterial(stone1,stone).
hasMaterial(stone2,stone).
hasMaterial(stone3,stone).
hasMaterial(stone6,stone).
hasMaterial(wood0,wood).
hasMaterial(wood4,wood).
hasMaterial(wood5,wood).
hasOrientation(stone1,vertical).
hasOrientation(stone2,vertical).
hasOrientation(stone3,horizontal).
hasOrientation(stone6,vertical).
hasOrientation(wood0,horizontal).
hasOrientation(wood4,horizontal).
hasOrientation(wood5,horizontal).
hasSize(pig0,small).
hasSize(stone1,big).
hasSize(stone2,big).
hasSize(stone3,big).
hasSize(stone6,big).
hasSize(wood0,big).
hasSize(wood4,medium).
hasSize(wood5,big).
hill(hill0).
isAnchorPointFor(stone2,struct1).
isAnchorPointFor(stone3,struct2).
isAnchorPointFor(wood0,struct0).
isAnchorPointFor(wood4,struct3).
isAnchorPointFor(wood5,struct4).
isBelow(stone1,wood0).
isBelow(stone6,wood5).
isBelow(wood5,pig0).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isHittable(pig0,true).
isHittable(stone1,true).
isHittable(stone2,true).
isHittable(stone3,true).
isHittable(stone6,true).
isHittable(wood0,true).
isHittable(wood4,true).
isHittable(wood5,true).
isLeft(dummyObject,dummmyObject).
isOn(pig0,wood5).
isOn(stone1,hill0).
isOn(stone2,hill0).
isOn(stone3,hill0).
isOn(stone6,hill0).
isOn(wood0,stone1).
isOn(wood4,hill0).
isOn(wood5,stone6).
isRight(dummyObject,dummmyObject).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
structure(struct4).
supports(dummyObject,dummmyObject).
