belongsTo(pig0,struct1).
belongsTo(pig1,struct2).
belongsTo(stone1,struct3).
belongsTo(stone2,struct3).
belongsTo(stone3,struct4).
belongsTo(wood0,struct0).
belongsTo(wood4,struct4).
bird(redbird0).
bird(redbird1).
bird(redbird2).
birdOrder(redbird0,1).
birdOrder(redbird1,2).
birdOrder(redbird2,0).
canCollapse(struct0,struct1).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
hasColor(redbird0,red).
hasColor(redbird1,red).
hasColor(redbird2,red).
hasForm(stone1,block).
hasForm(stone2,bar).
hasForm(stone3,bar).
hasForm(wood0,ball).
hasForm(wood4,block).
hasMaterial(stone1,stone).
hasMaterial(stone2,stone).
hasMaterial(stone3,stone).
hasMaterial(wood0,wood).
hasMaterial(wood4,wood).
hasOrientation(stone1,horizontal).
hasOrientation(stone2,horizontal).
hasOrientation(stone3,vertical).
hasOrientation(wood0,horizontal).
hasOrientation(wood4,vertical).
hasSize(pig0,small).
hasSize(pig1,small).
hasSize(stone1,medium).
hasSize(stone2,big).
hasSize(stone3,medium).
hasSize(wood0,medium).
hasSize(wood4,medium).
hill(hill0).
isAnchorPointFor(pig0,struct1).
isAnchorPointFor(pig1,struct2).
isAnchorPointFor(stone1,struct3).
isAnchorPointFor(stone3,struct4).
isAnchorPointFor(wood0,struct0).
isBelow(dummyObject,dummmyObject).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isHittable(pig0,true).
isHittable(pig1,true).
isHittable(stone1,true).
isHittable(stone2,true).
isHittable(stone3,true).
isHittable(wood0,true).
isHittable(wood4,true).
isLeft(stone1,stone2).
isLeft(stone3,wood4).
isOn(pig0,ground).
isOn(pig1,ground).
isOn(stone1,ground).
isOn(stone2,ground).
isOn(stone3,ground).
isOn(wood0,hill0).
isOn(wood4,ground).
isRight(stone2,stone1).
isRight(wood4,stone3).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
structure(struct4).
supports(stone1,stone2).
supports(stone3,wood4).
supports(wood4,stone3).
