belongsTo(ice0,struct1).
belongsTo(ice11,struct1).
belongsTo(ice6,struct1).
belongsTo(ice7,struct1).
belongsTo(pig0,struct0).
belongsTo(stone3,struct1).
belongsTo(stone4,struct1).
belongsTo(stone9,struct1).
belongsTo(wood1,struct1).
belongsTo(wood10,struct1).
belongsTo(wood2,struct1).
belongsTo(wood5,struct1).
belongsTo(wood8,struct1).
bird(redbird0).
bird(redbird1).
bird(redbird2).
birdOrder(redbird0,1).
birdOrder(redbird1,2).
birdOrder(redbird2,0).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
hasColor(redbird0,red).
hasColor(redbird1,red).
hasColor(redbird2,red).
hasForm(ice0,block).
hasForm(ice11,bar).
hasForm(ice6,bar).
hasForm(ice7,block).
hasForm(stone3,bar).
hasForm(stone4,bar).
hasForm(stone9,bar).
hasForm(wood1,bar).
hasForm(wood10,bar).
hasForm(wood2,cube).
hasForm(wood5,bar).
hasForm(wood8,block).
hasMaterial(ice0,glass).
hasMaterial(ice11,glass).
hasMaterial(ice6,glass).
hasMaterial(ice7,glass).
hasMaterial(stone3,stone).
hasMaterial(stone4,stone).
hasMaterial(stone9,stone).
hasMaterial(wood1,wood).
hasMaterial(wood10,wood).
hasMaterial(wood2,wood).
hasMaterial(wood5,wood).
hasMaterial(wood8,wood).
hasOrientation(ice0,vertical).
hasOrientation(ice11,vertical).
hasOrientation(ice6,vertical).
hasOrientation(ice7,horizontal).
hasOrientation(stone3,vertical).
hasOrientation(stone4,horizontal).
hasOrientation(stone9,vertical).
hasOrientation(wood1,vertical).
hasOrientation(wood10,vertical).
hasOrientation(wood2,horizontal).
hasOrientation(wood5,horizontal).
hasOrientation(wood8,horizontal).
hasSize(ice0,medium).
hasSize(ice11,big).
hasSize(ice6,medium).
hasSize(ice7,medium).
hasSize(pig0,small).
hasSize(stone3,medium).
hasSize(stone4,big).
hasSize(stone9,medium).
hasSize(wood1,big).
hasSize(wood10,medium).
hasSize(wood2,small).
hasSize(wood5,medium).
hasSize(wood8,medium).
hill(hill0).
isAnchorPointFor(ice0,struct1).
isAnchorPointFor(pig0,struct0).
isBelow(ice11,ice7).
isBelow(stone3,ice0).
isBelow(stone3,stone4).
isBelow(stone3,wood2).
isBelow(stone4,wood5).
isBelow(stone9,stone4).
isBelow(stone9,wood8).
isBelow(wood1,ice0).
isBelow(wood1,stone4).
isBelow(wood1,wood2).
isBelow(wood10,stone4).
isBelow(wood10,wood8).
isBelow(wood5,ice6).
isCollapsable(struct0).
isCollapsable(struct1).
isHittable(ice0,true).
isHittable(ice6,true).
isHittable(ice7,true).
isHittable(stone4,true).
isHittable(wood2,true).
isHittable(wood5,true).
isLeft(ice0,ice6).
isLeft(ice6,ice7).
isLeft(wood1,stone3).
isLeft(wood10,ice11).
isLeft(wood2,wood5).
isLeft(wood5,wood8).
isLeft(wood8,ice11).
isOn(ice0,stone3).
isOn(ice0,wood1).
isOn(ice11,hill0).
isOn(ice6,wood5).
isOn(ice7,ice11).
isOn(pig0,hill0).
isOn(stone3,hill0).
isOn(stone4,stone3).
isOn(stone4,stone9).
isOn(stone4,wood1).
isOn(stone4,wood10).
isOn(stone9,hill0).
isOn(wood1,hill0).
isOn(wood10,hill0).
isOn(wood2,stone3).
isOn(wood2,wood1).
isOn(wood5,stone4).
isOn(wood8,stone9).
isOn(wood8,wood10).
isOver(pig0,stone4).
isRight(ice11,wood10).
isRight(ice11,wood8).
isRight(ice6,ice0).
isRight(ice7,ice6).
isRight(stone3,wood1).
isRight(wood5,wood2).
isRight(wood8,wood5).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
protects(struct1,pig0).
structure(struct0).
structure(struct1).
supports(ice0,ice6).
supports(ice11,wood10).
supports(ice11,wood8).
supports(ice6,ice0).
supports(ice6,ice7).
supports(ice7,ice6).
supports(stone3,wood1).
supports(wood1,stone3).
supports(wood10,ice11).
supports(wood2,wood5).
supports(wood8,ice11).
supports(wood8,wood5).
