belongsTo(ice10,struct0).
belongsTo(ice5,struct0).
belongsTo(pig0,struct0).
belongsTo(stone8,struct0).
belongsTo(wood0,struct0).
belongsTo(wood1,struct0).
belongsTo(wood11,struct0).
belongsTo(wood12,struct0).
belongsTo(wood13,struct1).
belongsTo(wood2,struct0).
belongsTo(wood3,struct0).
belongsTo(wood4,struct0).
belongsTo(wood6,struct0).
belongsTo(wood7,struct0).
belongsTo(wood9,struct0).
bird(redbird0).
bird(redbird1).
birdOrder(redbird0,0).
birdOrder(redbird1,1).
canCollapse(struct0,struct1).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
hasColor(redbird0,red).
hasColor(redbird1,red).
hasForm(ice10,bar).
hasForm(ice5,bar).
hasForm(stone8,block).
hasForm(wood0,bar).
hasForm(wood1,bar).
hasForm(wood11,bar).
hasForm(wood12,bar).
hasForm(wood13,bar).
hasForm(wood2,bar).
hasForm(wood3,bar).
hasForm(wood4,bar).
hasForm(wood6,bar).
hasForm(wood7,bar).
hasForm(wood9,block).
hasMaterial(ice10,glass).
hasMaterial(ice5,glass).
hasMaterial(stone8,stone).
hasMaterial(wood0,wood).
hasMaterial(wood1,wood).
hasMaterial(wood11,wood).
hasMaterial(wood12,wood).
hasMaterial(wood13,wood).
hasMaterial(wood2,wood).
hasMaterial(wood3,wood).
hasMaterial(wood4,wood).
hasMaterial(wood6,wood).
hasMaterial(wood7,wood).
hasMaterial(wood9,wood).
hasOrientation(ice10,vertical).
hasOrientation(ice5,vertical).
hasOrientation(stone8,vertical).
hasOrientation(wood0,horizontal).
hasOrientation(wood1,vertical).
hasOrientation(wood11,vertical).
hasOrientation(wood12,vertical).
hasOrientation(wood13,vertical).
hasOrientation(wood2,vertical).
hasOrientation(wood3,horizontal).
hasOrientation(wood4,horizontal).
hasOrientation(wood6,horizontal).
hasOrientation(wood7,horizontal).
hasOrientation(wood9,vertical).
hasSize(ice10,big).
hasSize(ice5,big).
hasSize(pig0,small).
hasSize(stone8,medium).
hasSize(wood0,big).
hasSize(wood1,big).
hasSize(wood11,big).
hasSize(wood12,big).
hasSize(wood13,medium).
hasSize(wood2,big).
hasSize(wood3,big).
hasSize(wood4,big).
hasSize(wood6,big).
hasSize(wood7,medium).
hasSize(wood9,medium).
hill(dummyObject).
isAnchorPointFor(wood0,struct0).
isAnchorPointFor(wood13,struct1).
isBelow(ice10,wood4).
isBelow(ice5,wood4).
isBelow(stone8,wood9).
isBelow(wood0,wood11).
isBelow(wood0,wood2).
isBelow(wood0,wood7).
isBelow(wood1,wood0).
isBelow(wood11,wood6).
isBelow(wood12,wood0).
isBelow(wood2,wood6).
isBelow(wood3,ice10).
isBelow(wood3,ice5).
isBelow(wood6,stone8).
isBelow(wood7,pig0).
isCollapsable(struct0).
isCollapsable(struct1).
isHittable(ice5,true).
isHittable(pig0,true).
isHittable(stone8,true).
isHittable(wood0,true).
isHittable(wood1,true).
isHittable(wood12,true).
isHittable(wood2,true).
isHittable(wood3,true).
isHittable(wood4,true).
isHittable(wood6,true).
isHittable(wood7,true).
isHittable(wood9,true).
isLeft(pig0,wood11).
isLeft(wood1,wood2).
isLeft(wood1,wood3).
isLeft(wood11,wood12).
isLeft(wood2,wood7).
isLeft(wood7,wood11).
isOn(ice10,wood3).
isOn(ice5,wood3).
isOn(pig0,wood7).
isOn(stone8,wood6).
isOn(wood0,wood1).
isOn(wood0,wood12).
isOn(wood1,ground).
isOn(wood11,wood0).
isOn(wood12,ground).
isOn(wood13,ground).
isOn(wood2,wood0).
isOn(wood3,ground).
isOn(wood4,ice10).
isOn(wood4,ice5).
isOn(wood6,wood11).
isOn(wood6,wood2).
isOn(wood7,wood0).
isOn(wood9,stone8).
isOver(pig0,wood2).
isRight(wood11,pig0).
isRight(wood11,wood7).
isRight(wood12,wood11).
isRight(wood2,wood1).
isRight(wood3,wood1).
isRight(wood7,wood2).
object(X) :- hasMaterial(X,_).
object(X) :- pig(X).
pig(pig0).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
supports(wood1,wood2).
supports(wood1,wood3).
supports(wood11,pig0).
supports(wood11,wood12).
supports(wood11,wood7).
supports(wood12,wood11).
supports(wood2,wood1).
supports(wood2,wood7).
