belongsTo(ice11,struct1).
belongsTo(ice14,struct1).
belongsTo(ice15,struct1).
belongsTo(ice3,struct0).
belongsTo(ice4,struct0).
belongsTo(ice7,struct0).
belongsTo(pig0,struct0).
belongsTo(stone0,struct0).
belongsTo(stone1,struct0).
belongsTo(stone10,struct1).
belongsTo(stone12,struct1).
belongsTo(stone6,struct0).
belongsTo(stone9,struct1).
belongsTo(wood13,struct1).
belongsTo(wood2,struct0).
belongsTo(wood5,struct0).
belongsTo(wood8,struct0).
bird(redbird0).
birdOrder(redbird0,0).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
hasColor(redbird0,red).
hasForm(ice11,block).
hasForm(ice14,block).
hasForm(ice15,block).
hasForm(ice3,bar).
hasForm(ice4,bar).
hasForm(ice7,bar).
hasForm(stone0,bar).
hasForm(stone1,bar).
hasForm(stone10,bar).
hasForm(stone12,block).
hasForm(stone6,bar).
hasForm(stone9,block).
hasForm(wood13,cube).
hasForm(wood2,cube).
hasForm(wood5,cube).
hasForm(wood8,cube).
hasMaterial(ice11,glass).
hasMaterial(ice14,glass).
hasMaterial(ice15,glass).
hasMaterial(ice3,glass).
hasMaterial(ice4,glass).
hasMaterial(ice7,glass).
hasMaterial(stone0,stone).
hasMaterial(stone1,stone).
hasMaterial(stone10,stone).
hasMaterial(stone12,stone).
hasMaterial(stone6,stone).
hasMaterial(stone9,stone).
hasMaterial(wood13,wood).
hasMaterial(wood2,wood).
hasMaterial(wood5,wood).
hasMaterial(wood8,wood).
hasOrientation(ice11,horizontal).
hasOrientation(ice14,horizontal).
hasOrientation(ice15,vertical).
hasOrientation(ice3,vertical).
hasOrientation(ice4,horizontal).
hasOrientation(ice7,vertical).
hasOrientation(stone0,horizontal).
hasOrientation(stone1,horizontal).
hasOrientation(stone10,horizontal).
hasOrientation(stone12,horizontal).
hasOrientation(stone6,horizontal).
hasOrientation(stone9,horizontal).
hasOrientation(wood13,horizontal).
hasOrientation(wood2,horizontal).
hasOrientation(wood5,horizontal).
hasOrientation(wood8,horizontal).
hasSize(ice11,medium).
hasSize(ice14,medium).
hasSize(ice15,medium).
hasSize(ice3,big).
hasSize(ice4,big).
hasSize(ice7,big).
hasSize(pig0,small).
hasSize(stone0,big).
hasSize(stone1,big).
hasSize(stone10,big).
hasSize(stone12,medium).
hasSize(stone6,big).
hasSize(stone9,medium).
hasSize(wood13,small).
hasSize(wood2,small).
hasSize(wood5,small).
hasSize(wood8,small).
hill(hill0).
hill(hill1).
hill(hill2).
isAnchorPointFor(stone1,struct0).
isAnchorPointFor(stone10,struct1).
isBelow(ice14,ice15).
isBelow(ice15,stone12).
isBelow(ice3,ice4).
isBelow(ice4,wood2).
isBelow(ice4,wood5).
isBelow(ice4,wood8).
isBelow(ice7,ice4).
isBelow(stone0,stone1).
isBelow(stone1,ice3).
isBelow(stone1,ice7).
isBelow(stone1,pig0).
isBelow(stone10,ice11).
isBelow(stone10,wood13).
isBelow(stone12,stone10).
isBelow(stone6,stone1).
isBelow(stone9,stone10).
isCollapsable(struct0).
isCollapsable(struct1).
isHittable(ice11,true).
isHittable(ice3,true).
isHittable(ice4,true).
isHittable(ice7,true).
isHittable(pig0,true).
isHittable(stone0,true).
isHittable(stone1,true).
isHittable(stone10,true).
isHittable(stone6,true).
isHittable(stone9,true).
isHittable(wood2,true).
isHittable(wood5,true).
isHittable(wood8,true).
isLeft(ice11,wood13).
isLeft(stone0,stone6).
isLeft(stone9,stone12).
isOn(ice11,stone10).
isOn(ice14,ground).
isOn(ice15,ice14).
isOn(ice3,stone1).
isOn(ice4,ice3).
isOn(ice4,ice7).
isOn(ice7,stone1).
isOn(pig0,stone1).
isOn(stone0,hill0).
isOn(stone1,stone0).
isOn(stone1,stone6).
isOn(stone10,stone12).
isOn(stone10,stone9).
isOn(stone12,ice15).
isOn(stone6,hill0).
isOn(stone9,hill1).
isOn(wood13,stone10).
isOn(wood2,ice4).
isOn(wood5,ice4).
isOn(wood8,ice4).
isOver(pig0,ice4).
isRight(stone12,stone9).
isRight(stone6,stone0).
isRight(wood13,ice11).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
supports(ice11,wood13).
